default: &default
  adapter: postgresql
  encoding: utf8
  host: localhost
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: adc2023_08_dev

test:
  <<: *default
  database: adc2023_08_test

production:
  <<: *default
  database: adc2023_08_production
